### ISSUE TITLE
application.yml파일 설정값 적용이슈

### ISSUE THREAD

**Issue by zerodkdj** [MangKyu/spring-boot-test-automock#1]
안녕하세요 토이프로젝트에서 사용중발견한 이슈입니다.
automock기능을 비활성화하기위해 yml설정파일에 false로 설정해두었는데 적용이 안됩니다.

`
io:
  github:
    mangkyu:
      automock:
         enable: false
`

코드를 분석해보니 작성하신 properties파일에 io.github.mangkyu.automock.enable default값이 true로되있던데,
AutoMockAutoConfiguration클래스의 빈을 생성하는 과정중 
`@ConditionalOnProperty(name = "io.github.mangkyu.automock.enable", havingValue = "true")` 어노테이션을 적용하면서 문제가 발생하는거 같습니다.

@ConditionalOnProperty는 OnPropertyCondition클래스를 실행하고 적용되는 메소드는 아래와같습니다.

`
                                                 private void collectProperties(PropertyResolver resolver, List<String> missing, List<String> nonMatching) {
                     
                 for (String name : this.names) {
				String key = this.prefix + name;
				if (resolver.containsProperty(key)) {
					if (!isMatch(resolver.getProperty(key), this.havingValue)) {
						nonMatching.add(name);
					}
				}
				else {
					if (!this.matchIfMissing) {
						missing.add(name);
					}
				}
			}
		}
`
collectProperties메소드에서 프로퍼티값을 수집하여 적용여부를 확인하는데 해당 메소드에서
yml파일로로 작성한 설정값과 라이브러리에서 property파일로작성된 설정값이 둘다 수집이됩니다.

<img width="1013" alt="KakaoTalk_20220902_001208453" src="https://user-images.githubusercontent.com/13767077/187954826-d0e59d1c-15f2-40bc-8cfb-b4762e760463.png">

이 부분에서 우선순위가 라이브러리에서 작성된 properties파일이 더 높아서 사용자가 작성한 yml값이 적용이 안되는 이슈가 발생합니다.  yml파일이 아니라 properties파일로 작성하면 라이브러리에서 작성된값이 덮어쓰기가되어 적용이 되지만 yml파일은 적용이 안되고 있습니다.

**Comment by MangKyu** [comment]
안녕하세요! 오우 이거를 어떻게 보고 사용하셨는지 감사합니다ㅎㅎ
말씀해주신 케이스는 제가 고려하지 못했네요! 기존에 있던 프로퍼티 제거하고 0.05로 재배포했습니다!
감사합니다:)
